learning_templates/basic_app/urls.py
from django.urls import path

from basic_app import views


# Templates Tagging

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {"text": "hello world", "numbers":100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_template.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container" class="navbar-nav">
        <a class=" nav-item navbar-brand" href="{% url 'index' %}">Brand</a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-header nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
          </li>

        </ul>

      </div>
    </nav>
    <div class="container">

      {% block body_block %}
      <!-- anything ouside of this will be inherited if you extend-->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
   {% block body_block %}
    <h1>Welcome to index</h1>
    <!-- <h1>This is index.html page showing</h1> -->
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ numbers|add:"70" }}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
   {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of templates inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative uel template</h1>
    <a href="{% url 'basic_app:other' %}"> THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">Link To Admin Page</a>
    <a href="{% url 'index' %}">Link to index</a>

  </body>
</html>